### ISSUE TITLE
feat/example error

### ISSUE THREAD

**Issue by olzii** [Blancduman/mediasoup-client-flutter#6]
Hi all, 

Are there anyone who tried feat/example ? It is not complete, gives some type errors : 

`Debug service listening on ws://127.0.0.1:50020/mFMvVhL3x3E=/ws
[Logger::WebTransport] DEBUG: constructor() [url:wss://v3demo.mediasoup.org:4443/?roomId=1&peerId=zxcvvczx, options:null]
[Peer] DEBUG: constructor()
[Logger::WebTransport] DEBUG: onOpen
[Peer] DEBUG: emit "open"
[Peer] DEBUG: request() [method:getRouterRtpCapabilities, id: 2309840]
{codecs: [{kind: audio, mimeType: audio/opus, clockRate: 48000, channels: 2, rtcpFeedback: [{type: transport-cc, parameter: }], parameters: {useinbandfec: 1, stereo: 1}, preferredPayloadType: 100}, {kind: video, mimeType: video/VP8, clockRate: 90000, rtcpFeedback: [{type: nack, parameter: }, {type: nack, parameter: pli}, {type: ccm, parameter: fir}, {type: goog-remb, parameter: }, {type: transport-cc, parameter: }], parameters: {x-google-start-bitrate: 1500}, preferredPayloadType: 101}, {kind: video, mimeType: video/rtx, preferredPayloadType: 102, clockRate: 90000, parameters: {apt: 101}, rtcpFeedback: []}, {kind: video, mimeType: video/H264, clockRate: 90000, parameters: {packetization-mode: 1, level-asymmetry-allowed: 1, profile-level-id: 42e032}, rtcpFeedback: [{type: nack, parameter: }, {type: nack, parameter: pli}, {type: ccm, parameter: fir}, {type: goog-remb, parameter: }, {type: transport-cc, parameter: }], preferredPayloadType: 103}, {kind: video, mimeType: video/rtx, preferredPayloadType: 104, clockRate: 90000, parameters: {apt: 103}, rtcpFeedback: []}, {kind: video, mimeType: video/VP9, clockRate: 90000, rtcpFeedback: [{type: nack, parameter: }, {type: nack, parameter: pli}, {type: ccm, parameter: fir}, {type: goog-remb, parameter: }, {type: transport-cc, parameter: }], parameters: {x-google-start-bitrate: 1500}, preferredPayloadType: 105}, {kind: video, mimeType: video/rtx, preferredPayloadType: 106, clockRate: 90000, parameters: {apt: 105}, rtcpFeedback: []}], headerExtensions: [{kind: audio, uri: urn:ietf:params:rtp-hdrext:sdes:mid, preferredId: 1, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: urn:ietf:params:rtp-hdrext:sdes:mid, preferredId: 1, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id, preferredId: 2, preferredEncrypt: false, direction: recvonly}, {kind: video, uri: urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id, preferredId: 3, preferredEncrypt: false, direction: recvonly}, {kind: audio, uri: http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time, preferredId: 4, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time, preferredId: 4, preferredEncrypt: false, direction: sendrecv}, {kind: audio, uri: http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01, preferredId: 5, preferredEncrypt: false, direction: recvonly}, {kind: video, uri: http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01, preferredId: 5, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07, preferredId: 6, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: urn:ietf:params:rtp-hdrext:framemarking, preferredId: 7, preferredEncrypt: false, direction: sendrecv}, {kind: audio, uri: urn:ietf:params:rtp-hdrext:ssrc-audio-level, preferredId: 10, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: urn:3gpp:video-orientation, preferredId: 11, preferredEncrypt: false, direction: sendrecv}, {kind: video, uri: urn:ietf:params:rtp-hdrext:toffset, preferredId: 12, preferredEncrypt: false, direction: sendrecv}]}
mediasoup-client:Device load() [routerRtpCapabilities:Instance of 'RtpCapabilities']
mediasoup-client:Browser getNativeRtpCapabilities()
SdpTransform: trying to add null key
parsed: {version: 0, origin: {username: -, sessionId: 7340973776351648000, sessionVersion: 2, netType: IN, ipVer: 4, address: 127.0.0.1}, name: -, invalid: [{value: -}, {value: extmap-allow-mixed}], timing: {start: 0, stop: 0}, groups: [{type: BUNDLE, mids: 0 1}], msidSemantic: {semantic: null, token: WMS}, media: [{rtp: [{payload: 111, codec: opus, rate: 48000, encoding: 2}, {payload: 103, codec: ISAC, rate: 16000, encoding: null}, {payload: 104, codec: ISAC, rate: 32000, encoding: null}, {payload: 9, codec: G722, rate: 8000, encoding: null}, {payload: 0, codec: PCMU, rate: 8000, encoding: null}, {payload: 8, codec: PCMA, rate: 8000, encoding: null}, {payload: 106, codec: CN, rate: 32000, encoding: null}, {payload: 105, codec: CN, rate: 16000, encoding: null}, {payload: 13, codec: CN, rate: 8000, encoding: null}, {payload: 110, codec: telephone-event, rate: 48000, encoding: null}, {payload: 112, codec: telephone-event, rate: 32000, encoding: null}, {payload: 113, codec: telephone-event, rate: 16000, encoding: null}, {payload: 126, codec: telephone-event, rate: 8000, encoding: null}], fmtp: [{payload: 111, config: minptime=10;useinbandfec=1}], type: audio, port: 9, protocol: UDP/TLS/RTP/SAVPF, payloads: 111 103 104 9 0 8 106 105 13 110 112 113 126, connection: {version: 4, ip: 0.0.0.0}, rtcp: {port: 9, netType: IN, ipVer: 4, address: 0.0.0.0}, iceUfrag: xTAe, icePwd: ATHm2EYb8Tr46rQEzXX6X0Mu, iceOptions: trickle, fingerprint: {type: sha-256, hash: 5D:EB:BD:B5:4B:E3:E0:F2:F8:8E:CD:01:49:63:47:FD:9D:10:2D:03:84:B2:F6:B6:1B:A2:EF:36:12:B1:C1:71}, setup: actpass, mid: 0, ext: [{value: 1, direction: null, uri: urn:ietf:params:rtp-hdrext:ssrc-audio-level, config: null}, {value: 2, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time, config: null}, {value: 3, direction: null, uri: http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01, config: null}, {value: 4, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:mid, config: null}, {value: 5, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id, config: null}, {value: 6, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id, config: null}], direction: sendrecv, msid: - cfd87847-d834-4b11-be64-141e3aedcdf0, rtcpMux: rtcp-mux, rtcpFb: [{payload: 111, type: transport-cc, subtype: null}], ssrcs: [{id: 3993446316, attribute: cname, value: 2vCenoo+cznp2Rdl}, {id: 3993446316, attribute: msid, value: - cfd87847-d834-4b11-be64-141e3aedcdf0}, {id: 3993446316, attribute: mslabel, value: -}, {id: 3993446316, attribute: label, value: cfd87847-d834-4b11-be64-141e3aedcdf0}]}, {rtp: [{payload: 96, codec: VP8, rate: 90000, encoding: null}, {payload: 97, codec: rtx, rate: 90000, encoding: null}, {payload: 98, codec: VP9, rate: 90000, encoding: null}, {payload: 99, codec: rtx, rate: 90000, encoding: null}, {payload: 100, codec: VP9, rate: 90000, encoding: null}, {payload: 101, codec: rtx, rate: 90000, encoding: null}, {payload: 102, codec: H264, rate: 90000, encoding: null}, {payload: 121, codec: rtx, rate: 90000, encoding: null}, {payload: 127, codec: H264, rate: 90000, encoding: null}, {payload: 120, codec: rtx, rate: 90000, encoding: null}, {payload: 125, codec: H264, rate: 90000, encoding: null}, {payload: 107, codec: rtx, rate: 90000, encoding: null}, {payload: 108, codec: H264, rate: 90000, encoding: null}, {payload: 109, codec: rtx, rate: 90000, encoding: null}, {payload: 35, codec: AV1X, rate: 90000, encoding: null}, {payload: 36, codec: rtx, rate: 90000, encoding: null}, {payload: 124, codec: H264, rate: 90000, encoding: null}, {payload: 119, codec: rtx, rate: 90000, encoding: null}, {payload: 123, codec: H264, rate: 90000, encoding: null}, {payload: 118, codec: rtx, rate: 90000, encoding: null}, {payload: 114, codec: red, rate: 90000, encoding: null}, {payload: 115, codec: rtx, rate: 90000, encoding: null}, {payload: 116, codec: ulpfec, rate: 90000, encoding: null}], fmtp: [{payload: 97, config: apt=96}, {payload: 98, config: profile-id=0}, {payload: 99, config: apt=98}, {payload: 100, config: profile-id=2}, {payload: 101, config: apt=100}, {payload: 102, config: level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f}, {payload: 121, config: apt=102}, {payload: 127, config: level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f}, {payload: 120, config: apt=127}, {payload: 125, config: level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f}, {payload: 107, config: apt=125}, {payload: 108, config: level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f}, {payload: 109, config: apt=108}, {payload: 36, config: apt=35}, {payload: 124, config: level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f}, {payload: 119, config: apt=124}, {payload: 123, config: level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f}, {payload: 118, config: apt=123}, {payload: 115, config: apt=114}], type: video, port: 9, protocol: UDP/TLS/RTP/SAVPF, payloads: 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123 118 114 115 116, connection: {version: 4, ip: 0.0.0.0}, rtcp: {port: 9, netType: IN, ipVer: 4, address: 0.0.0.0}, iceUfrag: xTAe, icePwd: ATHm2EYb8Tr46rQEzXX6X0Mu, iceOptions: trickle, fingerprint: {type: sha-256, hash: 5D:EB:BD:B5:4B:E3:E0:F2:F8:8E:CD:01:49:63:47:FD:9D:10:2D:03:84:B2:F6:B6:1B:A2:EF:36:12:B1:C1:71}, setup: actpass, mid: 1, ext: [{value: 14, direction: null, uri: urn:ietf:params:rtp-hdrext:toffset, config: null}, {value: 2, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time, config: null}, {value: 13, direction: null, uri: urn:3gpp:video-orientation, config: null}, {value: 3, direction: null, uri: http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01, config: null}, {value: 12, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/playout-delay, config: null}, {value: 11, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/video-content-type, config: null}, {value: 7, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/video-timing, config: null}, {value: 8, direction: null, uri: http://www.webrtc.org/experiments/rtp-hdrext/color-space, config: null}, {value: 4, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:mid, config: null}, {value: 5, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id, config: null}, {value: 6, direction: null, uri: urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id, config: null}], direction: sendrecv, msid: - 44eb3510-a237-4884-990f-05adde971299, rtcpMux: rtcp-mux, rtcpRsize: rtcp-rsize, rtcpFb: [{payload: 96, type: goog-remb, subtype: null}, {payload: 96, type: transport-cc, subtype: null}, {payload: 96, type: ccm, subtype: fir}, {payload: 96, type: nack, subtype: null}, {payload: 96, type: nack, subtype: pli}, {payload: 98, type: goog-remb, subtype: null}, {payload: 98, type: transport-cc, subtype: null}, {payload: 98, type: ccm, subtype: fir}, {payload: 98, type: nack, subtype: null}, {payload: 98, type: nack, subtype: pli}, {payload: 100, type: goog-remb, subtype: null}, {payload: 100, type: transport-cc, subtype: null}, {payload: 100, type: ccm, subtype: fir}, {payload: 100, type: nack, subtype: null}, {payload: 100, type: nack, subtype: pli}, {payload: 102, type: goog-remb, subtype: null}, {payload: 102, type: transport-cc, subtype: null}, {payload: 102, type: ccm, subtype: fir}, {payload: 102, type: nack, subtype: null}, {payload: 102, type: nack, subtype: pli}, {payload: 127, type: goog-remb, subtype: null}, {payload: 127, type: transport-cc, subtype: null}, {payload: 127, type: ccm, subtype: fir}, {payload: 127, type: nack, subtype: null}, {payload: 127, type: nack, subtype: pli}, {payload: 125, type: goog-remb, subtype: null}, {payload: 125, type: transport-cc, subtype: null}, {payload: 125, type: ccm, subtype: fir}, {payload: 125, type: nack, subtype: null}, {payload: 125, type: nack, subtype: pli}, {payload: 108, type: goog-remb, subtype: null}, {payload: 108, type: transport-cc, subtype: null}, {payload: 108, type: ccm, subtype: fir}, {payload: 108, type: nack, subtype: null}, {payload: 108, type: nack, subtype: pli}, {payload: 35, type: goog-remb, subtype: null}, {payload: 35, type: transport-cc, subtype: null}, {payload: 35, type: ccm, subtype: fir}, {payload: 35, type: nack, subtype: null}, {payload: 35, type: nack, subtype: pli}, {payload: 124, type: goog-remb, subtype: null}, {payload: 124, type: transport-cc, subtype: null}, {payload: 124, type: ccm, subtype: fir}, {payload: 124, type: nack, subtype: null}, {payload: 124, type: nack, subtype: pli}, {payload: 123, type: goog-remb, subtype: null}, {payload: 123, type: transport-cc, subtype: null}, {payload: 123, type: ccm, subtype: fir}, {payload: 123, type: nack, subtype: null}, {payload: 123, type: nack, subtype: pli}], ssrcGroups: [{semantics: FID, ssrcs: 173842415 11685779}], ssrcs: [{id: 173842415, attribute: cname, value: 2vCenoo+cznp2Rdl}, {id: 173842415, attribute: msid, value: - 44eb3510-a237-4884-990f-05adde971299}, {id: 173842415, attribute: mslabel, value: -}, {id: 173842415, attribute: label, value: 44eb3510-a237-4884-990f-05adde971299}, {id: 11685779, attribute: cname, value: 2vCenoo+cznp2Rdl}, {id: 11685779, attribute: msid, value: - 44eb3510-a237-4884-990f-05adde971299}, {id: 11685779, attribute: mslabel, value: -}, {id: 11685779, attribute: label, value: 44eb3510-a237-4884-990f-05adde971299}]}]}
mediasoup-client:Device load() | got native RTP capabilities:Instance of 'RtpCapabilities'
generateProfileLevelIdForAnswer() | result: [profile:1, level:31
mediasoup-client:Device load() | got extended RTP capabilities:Instance of 'ExtendedRtpCapabilities'
mediasoup-client:Device load() | got receiving RTP capabilities:Instance of 'RtpCapabilities'
mediasoup-client:Browser getNativeSctpCapabilities()
mediasoup-client:Device load() | got native SCTP capabilities:Instance of 'SctpCapabilities'
mediasoup-client:Device load() successed
mediasoup-client:Browser close()
_producetrue
[Peer] DEBUG: request() [method:createWebRtcTransport, id: 5994437]
mediasoup-client:Device createSendTransport()
mediasoup-client:Transport constructor() [id:a651c9da-bb61-48d3-b29a-6dcd4bd3531c, direction:send]
mediasoup-client:Browser run()
[Peer] DEBUG: request() [method:createWebRtcTransport, id: 9408153]
Error: Expected a value of type 'Map<String, dynamic>?', but got one of type 'LinkedMap<dynamic, dynamic>'
    at Object.throw_ [as throw] (http://localhost:49971/dart_sdk.js:5334:11)
    at Object.castError (http://localhost:49971/dart_sdk.js:5305:15)
    at Object.cast [as as] (http://localhost:49971/dart_sdk.js:5621:17)
    at dart.NullableType.new.as (http://localhost:49971/dart_sdk.js:7182:60)
    at Browser.Browser.new.run (http://localhost:49971/packages/mediasoup_client_flutter/src/handlers/sdp/PlanBUtils.dart.lib.js:4816:40)
    at run.next (<anonymous>)
    at runBody (http://localhost:49971/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:49971/dart_sdk.js:39083:7)
    at Browser.Browser.new.run (http://localhost:49971/packages/mediasoup_client_flutter/src/handlers/sdp/PlanBUtils.dart.lib.js:4794:20)
    at new Transport.Transport.new (http://localhost:49971/packages/mediasoup_client_flutter/src/handlers/sdp/PlanBUtils.dart.lib.js:6931:20)
    at Device.Device.new.[_createTransport] (http://localhost:49971/packages/mediasoup_client_flutter/src/Device.dart.lib.js:159:23)
    at Device.Device.new.createSendTransport (http://localhost:49971/packages/mediasoup_client_flutter/src/Device.dart.lib.js:180:36)
    at Device.Device.new.createSendTransportFromMap (http://localhost:49971/packages/mediasoup_client_flutter/src/Device.dart.lib.js:185:19)
    at room_client.RoomClient.new._joinRoom (http://localhost:49971/packages/example/room_client.dart.lib.js:194:59)
    at _joinRoom.next (<anonymous>)
    at http://localhost:49971/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:49971/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:49971/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:49971/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:49971/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:49971/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49971/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:49971/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:49971/dart_sdk.js:39182:13)
    at http://localhost:49971/dart_sdk.js:34689:9
mediasoup-client:Device createRecvTransport()
mediasoup-client:Transport constructor() [id:d1f2a362-8fc1-471e-8740-25ff9ec5e427, direction:recv]
mediasoup-client:Browser run()
[Peer] DEBUG: request() [method:join, id: 793603]
newConsumer request failed: Expected a value of type 'String', but got one of type 'int'
newConsumer request failed: Expected a value of type 'String', but got one of type 'int'
Error: Expected a value of type 'String', but got one of type 'int'
    at Object.throw_ [as throw] (http://localhost:49971/dart_sdk.js:5334:11)
    at room_client.RoomClient.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:288:27)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:49971/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:49971/dart_sdk.js:39083:7)
    at web_socket.WebSocket.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:274:79)
    at http://localhost:49971/packages/example/web_socket.dart.lib.js:130:19
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at peer.Peer.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:99:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at peer.Peer.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at peer.Peer.new.[_handleRequest] (http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:164:14)
    at http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:154:31
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebTransport.Transport.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:89:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at WebTransport.Transport.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at WebTransport.Transport.new.safeEmit (http://localhost:49971/packages/protoo_client/src/EnhancedEventEmitter.dart.lib.js:31:14)
    at http://localhost:49971/packages/protoo_client/src/transports/WebTransport.dart.lib.js:89:14
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebSocket.<anonymous> (http://localhost:49971/dart_sdk.js:105416:21)
Error: Expected a value of type 'String', but got one of type 'int'
    at Object.throw_ [as throw] (http://localhost:49971/dart_sdk.js:5334:11)
    at room_client.RoomClient.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:305:27)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:49971/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:49971/dart_sdk.js:39083:7)
    at web_socket.WebSocket.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:274:79)
    at http://localhost:49971/packages/example/web_socket.dart.lib.js:130:19
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at peer.Peer.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:99:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at peer.Peer.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at peer.Peer.new.[_handleRequest] (http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:164:14)
    at http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:154:31
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebTransport.Transport.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:89:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at WebTransport.Transport.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at WebTransport.Transport.new.safeEmit (http://localhost:49971/packages/protoo_client/src/EnhancedEventEmitter.dart.lib.js:31:14)
    at http://localhost:49971/packages/protoo_client/src/transports/WebTransport.dart.lib.js:89:14
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebSocket.<anonymous> (http://localhost:49971/dart_sdk.js:105416:21)
mediasoup-client:Transport produce() [track:Track(id: f657b080-7bcd-4c50-a6a3-87cc1fd7931f, kind: audio, label: Default - Microphone (4- USB2.0 MIC) (1908:2310), enabled: true, muted: false)
transport.produce()
mediasoup-client:Browser send() [kind:audio, tack.id:f657b080-7bcd-4c50-a6a3-87cc1fd7931f
Error: NoSuchMethodError: 'errorCallbackFun'
Dynamic call of null.
Receiver: Instance of 'FlexTaskAdd'
Arguments: [Instance of 'IndexError']
    at Object.throw_ [as throw] (http://localhost:49971/dart_sdk.js:5334:11)
    at Object.defaultNoSuchMethod (http://localhost:49971/dart_sdk.js:5779:15)
    at FlexQueue.FlexTaskAdd.new.noSuchMethod (http://localhost:49971/dart_sdk.js:6879:19)
    at Object.noSuchMethod (http://localhost:49971/dart_sdk.js:5775:30)
    at callNSM (http://localhost:49971/dart_sdk.js:5507:19)
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5509:27)
    at Object.callMethod (http://localhost:49971/dart_sdk.js:5587:17)
    at Object.dsend (http://localhost:49971/dart_sdk.js:5590:17)
    at FlexQueue.FlexQueue.new._runTask$ (http://localhost:49971/packages/mediasoup_client_flutter/src/FlexQueue/FlexQueue.dart.lib.js:189:68)
    at _runTask$.throw (<anonymous>)
    at http://localhost:49971/dart_sdk.js:39038:38
    at _RootZone.runBinary (http://localhost:49971/dart_sdk.js:38894:58)
    at _FutureListener.thenAwait.handleError (http://localhost:49971/dart_sdk.js:33887:48)
    at handleError (http://localhost:49971/dart_sdk.js:34451:51)
    at Function._propagateToListeners (http://localhost:49971/dart_sdk.js:34477:17)
    at _Future.new.[_completeError] (http://localhost:49971/dart_sdk.js:34323:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49971/dart_sdk.js:34362:31)
    at Object._microtaskLoop (http://localhost:49971/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:49971/dart_sdk.js:39182:13)
    at http://localhost:49971/dart_sdk.js:34689:9
newConsumer request failed: Expected a value of type 'String', but got one of type 'int'
Error: Expected a value of type 'String', but got one of type 'int'
    at Object.throw_ [as throw] (http://localhost:49971/dart_sdk.js:5334:11)
    at room_client.RoomClient.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:305:27)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:49971/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:49971/dart_sdk.js:39083:7)
    at web_socket.WebSocket.new.<anonymous> (http://localhost:49971/packages/example/room_client.dart.lib.js:274:79)
    at http://localhost:49971/packages/example/web_socket.dart.lib.js:130:19
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at peer.Peer.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:99:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at peer.Peer.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at peer.Peer.new.[_handleRequest] (http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:164:14)
    at http://localhost:49971/packages/protoo_client/src/peer.dart.lib.js:154:31
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebTransport.Transport.new.callback (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:89:18)
    at http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:186:14
    at Array.[dartx.forEach] (http://localhost:49971/dart_sdk.js:15666:11)
    at WebTransport.Transport.new.emit (http://localhost:49971/packages/events2/src/event_emitter.dart.lib.js:184:50)
    at WebTransport.Transport.new.safeEmit (http://localhost:49971/packages/protoo_client/src/EnhancedEventEmitter.dart.lib.js:31:14)
    at http://localhost:49971/packages/protoo_client/src/transports/WebTransport.dart.lib.js:89:14
    at Object._checkAndCall (http://localhost:49971/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:49971/dart_sdk.js:5549:17)
    at WebSocket.<anonymous> (http://localhost:49971/dart_sdk.js:105416:21)
`
I am testing it with demo mediasoup server. It connected successfully but no sound and video : 
![image_2021_05_17T09_09_35_269Z](https://user-images.githubusercontent.com/5012289/118464350-560f7200-b733-11eb-8b13-98cd69833da0.png)

Flutter screen : 
![image_2021_05_17T09_09_22_760Z](https://user-images.githubusercontent.com/5012289/118464402-645d8e00-b733-11eb-9512-842fc7a63114.png)

**Comment by Blancduman** [comment]
Im working on it, but do not commit. Tgere is some errors.

пн, 17 мая 2021 г., 12:15 olzii ***@***.***>:

**Comment by olzii** [comment]
@Blancduman When will you commit it ? Let's fix it together ?

**Comment by vishal-verma14** [comment]
hi @olzii @Blancduman ... is this issue fixed..

**Comment by Blancduman** [comment]
> hi @olzii @Blancduman ... is this issue fixed..

No. Busy with main job. Wait till the weekends.

**Comment by Blancduman** [comment]
@olzii @vishal-verma14 send transport for ios/android fixed. In example branch it's only contain video sending only for now.
Thank you very much @ZackMitkin and his [merge](https://github.com/Blancduman/mediasoup-client-flutter/pull/7)

**Comment by Blancduman** [comment]
A lot of work was done this weekend. There is still some issues. But sending and receiving streams for ios\android is done.

**Comment by Blancduman** [comment]
There is alittle issue. Probably, will fix it at weekends

**Comment by NicolaiLassen** [comment]
What is the status on the consumer. At the moment I can't get it to display a track.

Something like does the trick with the navigator media stream, but at the moment not with the consumer track :

var temp = await createLocalMediaStream("label");
await temp.addTrack(consumer.track);
_remoteRenderer.srcObject = temp;

**Comment by Blancduman** [comment]
@NicolaiLassen just try to add false to the if
[ScalabilityModes:13](https://github.com/Blancduman/mediasoup-client-flutter/blob/feat/example/lib/src/ScalabilityModes.dart#L13)
```dart
if (false && match.isNotEmpty) {
```

I messed up with regex,

and check example folder and @ZackMitkin PR

**Comment by NicolaiLassen** [comment]
@Blancduman Thanks, i will give it a go :)

**Comment by NicolaiLassen** [comment]
I can't seem to find the issue - not able to display the receiving stream (track).

I will keep you posted.

**Comment by Blancduman** [comment]
You need to make callback function as argument in transport creating
method. Once again, check example or leave it, until i write doc

пт, 28 мая 2021 г., 19:02 Nicolai Lassen ***@***.***>:
