### ISSUE TITLE
Transport.Produce(): type 'String' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by dkliss** [Blancduman/mediasoup-client-flutter#80]
Hi, 

I have been trying to get the media soup flutter client working. I am having an issue with below code, which is part of transport.produce(). The input needed for this is a List but if I add more than one item (i.e. uncomment the two items below), i get an error "type 'String' is not a subtype of type 'int'".  The error goes away if I only have one list item. I was wondering if this an issue. Any help is appreciated?

```
encodings: [
        RtpEncodingParameters(
            rid: 'r0', scalabilityMode: 'S1T3', maxBitrate: 100000),
        // RtpEncodingParameters(
        //     rid: 'r1', scalabilityMode: 'S1T3', maxBitrate: 300000),
        // RtpEncodingParameters(
        //     rid: 'r2', scalabilityMode: 'S1T3', maxBitrate: 900000)
      ],

```

I also tried below approach, but received same error:

```
encodings: [
    RtpEncodingParameters.fromMap({
      'rid': 'r0',
      'maxBitrate': 100000,
      'scalabilityMode': 'S1T3',
    }),
    RtpEncodingParameters.fromMap({
      'rid': 'r1',
      'maxBitrate': '300000',
      'scalabilityMode': 'S1T3',
    }),
    RtpEncodingParameters.fromMap({
      'rid': 'r2',
      'maxBitrate': '900000',
      'scalabilityMode': 'S1T3',
    }),
  ],
```

Errror Received. 

```
flutter: type 'String' is not a subtype of type 'int'
flutter: #0      Transport._produce (package:mediasoup_client_flutter/src/transport.dart:925:7)
<asynchronous suspension>
#1      FlexQueue._runTask (package:mediasoup_client_flutter/src/FlexQueue/flex_queue.dart:85:28)
<asynchronous suspension>
```

**Comment by Blancduman** [comment]
Will be able to after a couple days. Please, leave a way to communicate
with you

вт, 22 авг. 2023 г., 12:19 dk ***@***.***>:

**Comment by ambjn** [comment]
Hey @Blancduman , is the issue resolved?

**Comment by nhatbh** [comment]
I fixed it by using a local library and change the "id" in Rid to String from int
lib/src/handlers/sdp/media_section.dart:260
```
class Rid {
  final String id;
  final String direction;
  final String? params;

  Rid({
    required this.id,
    required this.direction,
    this.params,
  });

  Rid.fromMap(Map data)
      : id = data['id'],
        direction = data['direction'],
        params = data['params'];

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'direction': direction,
      'params': params,
    };
  }
}
```
This should be enough as a workaround waiting for the issue to be fixed
